"""New data

Revision ID: 046f9bebd41d
Revises: 257011798671
Create Date: 2023-05-10 22:54:03.237048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '046f9bebd41d'
down_revision = '257011798671'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('users',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('operation',
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('event', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
