"""New

Revision ID: 257011798671
Revises: 28f35ea2895a
Create Date: 2023-05-10 19:59:12.507056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257011798671'
down_revision = '28f35ea2895a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
